GET http://localhost:8002/films

###

/// CHARACTERS

GET http://localhost:8000/characters

####

POST  http://localhost:8004/Character
Content-Type: application/json

 {
"_id":"11119916611112666662111111111111111111",
"name":"ffffrddddddandd"
}

####

POST  http://localhost:8001/characters/create
Content-Type: application/json

 {
"_id":"420",
"name":"ffffrddddddandd"
}


###
POST  http://localhost:8000/characters/create
Content-Type: application/json

 {
"_id":"422",
"name":"frans"
}

####

GET http://localhost:8000/films


