// REQUEST TO GATEWAY - GET CHARACTERS

GET http://localhost:8000/characters

###

// REQUEST TO GATEWAY - GET Character by id

GET http://localhost:8000/characters/999

###


///REQUEST TO GATEWAY - POST CREATE CHARACTER
POST  http://localhost:8000/characters/create
Content-Type: application/json

 {
"_id":"9999",
"name":"francisco.sponton"
}

####


// REQUEST TO GATEWAY - GET FILMS

GET http://localhost:8000/films

###

// REQUEST TO GATEWAY - GET PLANETS

GET http://localhost:8000/planets

###

