# configuracion para orquestar todos los microservicios unidos.

version: '3'

services:
  gateway:
    container_name: gateway
    restart: always #Se reinicia siempre que falle
    build: ./gateway
    ports:
      - "8000:8000"

  characters:
    container_name: api-characters
    restart: always
    build: ./characters
    ports:
      - "8001:8001"

  films:
    container_name: api-films
    restart: always
    build: ./films
    ports:
      - "8002:8002"

  planets:
    container_name: api-planets
    restart: always
    build: ./planets
    ports:
      - "8003:8003"

  database:
    container_name: database
    restart: always
    build: ./database
    ports:
      - "8004:8004"
